# build environment
FROM node:14.17.6-alpine as build

WORKDIR /app

ENV AN_EXAMPLE=Prod

COPY package.json .
# COPY package-lock.json .

# RUN npm ci

RUN npm install

COPY . .

RUN npm run build

# production environment
FROM nginx:1.20.1-alpine as prod
COPY --from=build /app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]