# It starts the container: docker run
version: "3.9"

services:

  react-img-prod:
    container_name: react-container-prod

    build:
      context: .
      dockerfile: Dockerfile.prod
    
    ports:
      - "8080:80"

    environment:
      - AN_EXAMPLE=Prod
      - CHOKIDAR_USEPOLLING=true
    
    # --env-file ./env
    #env_file:
    #  - ./.env

    # -it
    #stdin_open: true
    #tty: true